services:
  mongodb:
    ports:
      - '27019:27017'
    volumes:
      - mongodb_data_prod:/data/db

  app:
    build:
      target: production
    ports:
      - '5000:5000'
    env_file:
      - .env
    environment:
      - PORT=5000
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=jobSearchApp_prod
    restart: always

volumes:
  mongodb_data_prod:
