name: 'CI Pipeline'
permissions:
  contents: read
  pull-requests: write

on: [push, pull_request, issues]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

  eslint:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

  prettier:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npm run format

  commit:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Check commit messages
        run: npx commitlint --from=HEAD --to=HEAD

  version-injection:
    runs-on: ubuntu-latest
    needs: [eslint, prettier, commit]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Inject Version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "Injecting version $VERSION into src/public/index.html"
          sed -i "s/{{VERSION}}/$VERSION/g" src/public/index.html

      - name: Verify Injection
        run: |
          grep -C 3 "id=\"app-version\"" src/public/index.html
